### ISSUE TITLE
cannot install in google colab

### ISSUE THREAD

**Issue by IRONYUNS** [dylanwal/numpy_dynamic_array#1]
Hello...currently I am unable to install dynamic array library in google colab...

so i try :
pip install numpy_dynamic_array

then the output in google colabs was :
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement numpy_dynamic_array (from versions: none)
ERROR: No matching distribution found for numpy_dynamic_array

I think this may because numpy==1.22.0

can I know how to fix this issue...

**Comment by dylanwal** [comment]
Likely this error arise because the Python version you are using is not Python 3.9 or above, and not because of numpy. 
Check out this for details on updating python version: 
https://stackoverflow.com/questions/68657341/how-can-i-update-google-colabs-python-version 

If that doesn't work, let me know.

**Comment by IRONYUNS** [comment]
Hello @dylanwal 

Yes, you are right...the real problem is my google colab run on python 3.7

So I try to run
!sudo apt-get update -y
!sudo apt-get install python3.9
!sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
!sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 2

And it says something like no pip install...So I install pip using:
!sudo apt install python3-pip

And some error still occur but i successfully solve it using:
!sudo apt install python3.9-distutils

and

!python3 -m pip install --upgrade pip

finally I was successfully install dynamic array library using
!pip install numpy_dynamic_array



But now....another issue appear... :(

So what I do was copy and paste your code from your github which was:

import numpy as np
from numpy_da import DynamicArray

data = DynamicArray(shape=2)
a = np.linspace(0, 9, 10)
data.append(a)  

print(data)  

The error was: 

ModuleNotFoundError: No module named 'numpy_da'


Its look like python cannot find numpy_da   ......

can you help me sir :(

**Comment by dylanwal** [comment]
Ok, after some troubleshooting. I know the issue is. The codes above don't actually change the python version.
If you run the following code:
`import sys`
`print(sys.version_info)`
-> `sys.version_info(major=3, minor=7, micro=13, releaselevel='final', serial=0)`  
so it is still python 3.7 even though `!python --version` says 3.9

So my solution was to modify my code to work with python 3.7 because I can't figure out how to get googlecolab to update to the new python.

run this code in a new notebook:
`%pip install https://github.com/dylanwal/numpy_dynamic_array/archive/python37.zip`
(this will pip install directly from the github branch made for python3.7)

**Comment by IRONYUNS** [comment]
Hello @dylanwal 

Thank you...Your solution work perfectly

The library you created was very helpful for me especially when involving streaming data algorithm.

Therefore, I hope you can continue your work in upgrading this library along the time.

Thank you again @dylanwal and have a good day. 👍 🥇
